STATUS_UPLOADED = 'UPLOADED'
STATUS_PROCESSING = 'PROCESSING'
STATUS_COMPLETED = 'COMPLETED'

file_status_choices = (
    (STATUS_UPLOADED, STATUS_UPLOADED),
    (STATUS_PROCESSING, STATUS_PROCESSING),
    (STATUS_COMPLETED, STATUS_COMPLETED),
)

DEFAULT_DOMAIN = 'gmail.com'
