# Generated by Django 4.0.1 on 2022-01-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='json_upload_files')),
                ('start_processing_time', models.DateTimeField(blank=True, null=True)),
                ('stop_processing_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('UPLOADED', 'UPLOADED'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED')], default='UPLOADED', max_length=20, null=True)),
                ('updated_number', models.IntegerField(default=0)),
                ('created_number', models.IntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
