# Generated by Django 4.0.1 on 2022-01-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
    ]
