# Generated by Django 4.0.1 on 2022-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='output_file'),
        ),
    ]
