# Generated by Django 4.0.1 on 2022-01-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_output_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created_number',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_number',
        ),
    ]
